apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: list-manager
  description: CDS list manager
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
