version: '3'

x-db-connection-strings: &db-connection-strings
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db/list-manager
  SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:postgres@test-db/list-manager

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.9"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        SHELLCHECK_VERSION: "0.7.2"
        SHELLCHECK_CHECKSUM: "70423609f27b504d6c0c47e340f33652aea975e45f312324f2dbf91c95a3b188"
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    environment:
      SHELL: /bin/zsh
      <<: *db-connection-strings

  api:
    build:
      context: ../api/
    volumes:
      - ../api:/function
    environment:
      <<: *db-connection-strings
      AWS_LOCALSTACK: "True"
      AXE_CORE_URLS_TOPIC: "arn:aws:sns:us-east-1:000000000000:axe-core-urls-topic"
      OPENAPI_URL: "/openapi.json"
 
  db:
    image: postgres:15.8@sha256:bf8657add1d8ba09904da03ddadd372443ff58bfe088c653e5b43bcb2cee2a10
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: list-manager
    expose:
      - "5433" 
    ports:
      - "5433:5432"
  
  test-db:
    image: postgres:15.8@sha256:bf8657add1d8ba09904da03ddadd372443ff58bfe088c653e5b43bcb2cee2a10
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: list-manager
    ports:
      - "5434:5432"
  
  localstack:
    image: localstack/localstack@sha256:1e783176f1b28c82a07fd3720e5a9d2f2d918b611ad0c1961044b4c033b5eb75
    hostname: localstack
    volumes:
      - "./data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init_localstack:/docker-entrypoint-initaws.d"
    ports:
      - 4566:4566 
      - 4571:4571
    environment:
      - SERVICES=s3,sns
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock`
      - DEBUG=1