name: Source code security scan using Bandit
on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    - name: Bandit
      run: |
        .github/workflows/scripts/run_bandit_scan.sh



