name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.12@sha256:9e9298817d19f4bd60c5028a25762b394db37dda173dd3d035a1bc155542051a
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: list-manager
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        folder: ["api"]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.13"

      - name: Setup node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "14"

      - name: Install dev dependencies
        working-directory: ${{ matrix.folder }}
        run: make install-dev

      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: make install

      - name: Lint
        working-directory: ${{ matrix.folder }}
        run: make lint-ci

      - name: Format
        working-directory: ${{ matrix.folder }}
        run: make fmt-ci

      - name: Test
        working-directory: ${{ matrix.folder }}
        env:
          SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@127.0.0.1/list-manager
          SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:postgres@127.0.0.1/list-manager
        run: make test
