name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.7@sha256:2d8059176e789c849701fc06d3f7834d4f6db52b74c89f7f3517c4540a3c38bd
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: list-manager
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        folder: ["api"]

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.9"

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "14"

      - name: Install dev dependencies
        working-directory: ${{ matrix.folder }}
        run: make install-dev

      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: make install

      - name: Lint
        working-directory: ${{ matrix.folder }}
        run: make lint-ci

      - name: Format
        working-directory: ${{ matrix.folder }}
        run: make fmt-ci

      - name: Test
        working-directory: ${{ matrix.folder }}
        env:
          SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@127.0.0.1/list-manager
          SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:postgres@127.0.0.1/list-manager
        run: make test
