name: Shellscripts PR Workflow
on:
  pull_request:
    paths:
      - "**/*.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Shellcheck
      run: .github/workflows/scripts/run_shellcheck.sh

  script_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Test Scripts
      run: .github/workflows/scripts/test_scripts.sh


